{% set version = "2021.9.0" %}
package:
  name: intake_pattern_catalog
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/intake-pattern-catalog/intake-pattern-catalog-{{ version }}.tar.gz
  sha256: 5f7d72619c1041ffcecbc713aa6abac3e591239625d37f59404faaa4cdacdc18

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - fsspec >=2021.4.0
    - intake
    - s3fs
    - boto3 ==1.17.49
    - msgpack-python

test:
  imports:
    - intake_pattern_catalog
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://bitbucket.org/dtnse/intake_pattern_catalog
  summary: Intake plugin for specifying a file-path pattern which can represent a number of different entries⏎
  license_file: LICENSE.md
  license: BSD-3-Clause

extra:
  recipe-maintainers:
    - tdhopper
    - blackary
